/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedEntradaRouteImport } from './routes/_authenticated/entrada'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminConteudosRouteImport } from './routes/_authenticated/admin.conteudos'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppDiarioRouteImport } from './routes/_authenticated/app.diario'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppProgressoRouteImport } from './routes/_authenticated/app.progresso'
import { Route as AuthenticatedAdminClienteClienteIdRouteImport } from './routes/_authenticated/admin.cliente.$clienteId'
import { Route as AuthenticatedAppConteudoConteudoIdRouteImport } from './routes/_authenticated/app.conteudo.$conteudoId'
import { Route as AuthenticatedAppEixoEixoIdRouteImport } from './routes/_authenticated/app.eixo.$eixoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntradaRoute = AuthenticatedEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConteudosRoute =
  AuthenticatedAdminConteudosRouteImport.update({
    id: '/conteudos',
    path: '/conteudos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiarioRoute = AuthenticatedAppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProgressoRoute =
  AuthenticatedAppProgressoRouteImport.update({
    id: '/progresso',
    path: '/progresso',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminClienteClienteIdRoute =
  AuthenticatedAdminClienteClienteIdRouteImport.update({
    id: '/cliente/$clienteId',
    path: '/cliente/$clienteId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppConteudoConteudoIdRoute =
  AuthenticatedAppConteudoConteudoIdRouteImport.update({
    id: '/conteudo/$conteudoId',
    path: '/conteudo/$conteudoId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEixoEixoIdRoute =
  AuthenticatedAppEixoEixoIdRouteImport.update({
    id: '/eixo/$eixoId',
    path: '/eixo/$eixoId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/entrada': typeof AuthenticatedEntradaRoute
  '/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/app/diario': typeof AuthenticatedAppDiarioRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/cliente/$clienteId': typeof AuthenticatedAdminClienteClienteIdRoute
  '/app/conteudo/$conteudoId': typeof AuthenticatedAppConteudoConteudoIdRoute
  '/app/eixo/$eixoId': typeof AuthenticatedAppEixoEixoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/app/diario': typeof AuthenticatedAppDiarioRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/cliente/$clienteId': typeof AuthenticatedAdminClienteClienteIdRoute
  '/app/conteudo/$conteudoId': typeof AuthenticatedAppConteudoConteudoIdRoute
  '/app/eixo/$eixoId': typeof AuthenticatedAppEixoEixoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/entrada': typeof AuthenticatedEntradaRoute
  '/_authenticated/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/_authenticated/app/diario': typeof AuthenticatedAppDiarioRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/cliente/$clienteId': typeof AuthenticatedAdminClienteClienteIdRoute
  '/_authenticated/app/conteudo/$conteudoId': typeof AuthenticatedAppConteudoConteudoIdRoute
  '/_authenticated/app/eixo/$eixoId': typeof AuthenticatedAppEixoEixoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/entrada'
    | '/admin/conteudos'
    | '/app/diario'
    | '/app/perfil'
    | '/app/progresso'
    | '/admin/'
    | '/app/'
    | '/admin/cliente/$clienteId'
    | '/app/conteudo/$conteudoId'
    | '/app/eixo/$eixoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/entrada'
    | '/admin/conteudos'
    | '/app/diario'
    | '/app/perfil'
    | '/app/progresso'
    | '/admin'
    | '/app'
    | '/admin/cliente/$clienteId'
    | '/app/conteudo/$conteudoId'
    | '/app/eixo/$eixoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/entrada'
    | '/_authenticated/admin/conteudos'
    | '/_authenticated/app/diario'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/progresso'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/cliente/$clienteId'
    | '/_authenticated/app/conteudo/$conteudoId'
    | '/_authenticated/app/eixo/$eixoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada': {
      id: '/_authenticated/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof AuthenticatedEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/conteudos': {
      id: '/_authenticated/admin/conteudos'
      path: '/conteudos'
      fullPath: '/admin/conteudos'
      preLoaderRoute: typeof AuthenticatedAdminConteudosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/diario': {
      id: '/_authenticated/app/diario'
      path: '/diario'
      fullPath: '/app/diario'
      preLoaderRoute: typeof AuthenticatedAppDiarioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progresso': {
      id: '/_authenticated/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AuthenticatedAppProgressoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/cliente/$clienteId': {
      id: '/_authenticated/admin/cliente/$clienteId'
      path: '/cliente/$clienteId'
      fullPath: '/admin/cliente/$clienteId'
      preLoaderRoute: typeof AuthenticatedAdminClienteClienteIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/conteudo/$conteudoId': {
      id: '/_authenticated/app/conteudo/$conteudoId'
      path: '/conteudo/$conteudoId'
      fullPath: '/app/conteudo/$conteudoId'
      preLoaderRoute: typeof AuthenticatedAppConteudoConteudoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/eixo/$eixoId': {
      id: '/_authenticated/app/eixo/$eixoId'
      path: '/eixo/$eixoId'
      fullPath: '/app/eixo/$eixoId'
      preLoaderRoute: typeof AuthenticatedAppEixoEixoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConteudosRoute: typeof AuthenticatedAdminConteudosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClienteClienteIdRoute: typeof AuthenticatedAdminClienteClienteIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConteudosRoute: AuthenticatedAdminConteudosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClienteClienteIdRoute:
    AuthenticatedAdminClienteClienteIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDiarioRoute: typeof AuthenticatedAppDiarioRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppProgressoRoute: typeof AuthenticatedAppProgressoRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppConteudoConteudoIdRoute: typeof AuthenticatedAppConteudoConteudoIdRoute
  AuthenticatedAppEixoEixoIdRoute: typeof AuthenticatedAppEixoEixoIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDiarioRoute: AuthenticatedAppDiarioRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppProgressoRoute: AuthenticatedAppProgressoRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppConteudoConteudoIdRoute:
    AuthenticatedAppConteudoConteudoIdRoute,
  AuthenticatedAppEixoEixoIdRoute: AuthenticatedAppEixoEixoIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedEntradaRoute: typeof AuthenticatedEntradaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedEntradaRoute: AuthenticatedEntradaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
