/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedEntradaRouteImport } from './routes/_authenticated/entrada'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAcompanhamentoRouteImport } from './routes/_authenticated/admin.acompanhamento'
import { Route as AuthenticatedAdminAjudaRouteImport } from './routes/_authenticated/admin.ajuda'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminConteudosRouteImport } from './routes/_authenticated/admin.conteudos'
import { Route as AuthenticatedAdminDiagnosticoRouteImport } from './routes/_authenticated/admin.diagnostico'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminInicioRouteImport } from './routes/_authenticated/admin.inicio'
import { Route as AuthenticatedAdminPacotesRouteImport } from './routes/_authenticated/admin.pacotes'
import { Route as AuthenticatedAdminPerfilRouteImport } from './routes/_authenticated/admin.perfil'
import { Route as AuthenticatedAdminTrilhasRouteImport } from './routes/_authenticated/admin.trilhas'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppDiarioRouteImport } from './routes/_authenticated/app.diario'
import { Route as AuthenticatedAppHistoricoRouteImport } from './routes/_authenticated/app.historico'
import { Route as AuthenticatedAppJornadaRouteImport } from './routes/_authenticated/app.jornada'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppProgressoRouteImport } from './routes/_authenticated/app.progresso'
import { Route as AuthenticatedAdminClienteClienteIdRouteImport } from './routes/_authenticated/admin.cliente.$clienteId'
import { Route as AuthenticatedAdminMonitoramentoIndexRouteImport } from './routes/_authenticated/admin.monitoramento.index'
import { Route as AuthenticatedAppConteudoConteudoIdRouteImport } from './routes/_authenticated/app.conteudo.$conteudoId'
import { Route as AuthenticatedAppEixoEixoIdRouteImport } from './routes/_authenticated/app.eixo.$eixoId'
import { Route as AuthenticatedAppEtapaConteudoIdRouteImport } from './routes/_authenticated/app.etapa.$conteudoId'
import { Route as ApiPublicHooksLembretesRouteImport } from './routes/api/public/hooks/lembretes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntradaRoute = AuthenticatedEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAcompanhamentoRoute =
  AuthenticatedAdminAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAjudaRoute = AuthenticatedAdminAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConteudosRoute =
  AuthenticatedAdminConteudosRouteImport.update({
    id: '/conteudos',
    path: '/conteudos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiagnosticoRoute =
  AuthenticatedAdminDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInicioRoute =
  AuthenticatedAdminInicioRouteImport.update({
    id: '/inicio',
    path: '/inicio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPacotesRoute =
  AuthenticatedAdminPacotesRouteImport.update({
    id: '/pacotes',
    path: '/pacotes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPerfilRoute =
  AuthenticatedAdminPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrilhasRoute =
  AuthenticatedAdminTrilhasRouteImport.update({
    id: '/trilhas',
    path: '/trilhas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiarioRoute = AuthenticatedAppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHistoricoRoute =
  AuthenticatedAppHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJornadaRoute = AuthenticatedAppJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProgressoRoute =
  AuthenticatedAppProgressoRouteImport.update({
    id: '/progresso',
    path: '/progresso',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminClienteClienteIdRoute =
  AuthenticatedAdminClienteClienteIdRouteImport.update({
    id: '/cliente/$clienteId',
    path: '/cliente/$clienteId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMonitoramentoIndexRoute =
  AuthenticatedAdminMonitoramentoIndexRouteImport.update({
    id: '/monitoramento/',
    path: '/monitoramento/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppConteudoConteudoIdRoute =
  AuthenticatedAppConteudoConteudoIdRouteImport.update({
    id: '/conteudo/$conteudoId',
    path: '/conteudo/$conteudoId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEixoEixoIdRoute =
  AuthenticatedAppEixoEixoIdRouteImport.update({
    id: '/eixo/$eixoId',
    path: '/eixo/$eixoId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEtapaConteudoIdRoute =
  AuthenticatedAppEtapaConteudoIdRouteImport.update({
    id: '/etapa/$conteudoId',
    path: '/etapa/$conteudoId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicHooksLembretesRoute = ApiPublicHooksLembretesRouteImport.update({
  id: '/api/public/hooks/lembretes',
  path: '/api/public/hooks/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/entrada': typeof AuthenticatedEntradaRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/acompanhamento': typeof AuthenticatedAdminAcompanhamentoRoute
  '/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/admin/diagnostico': typeof AuthenticatedAdminDiagnosticoRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/inicio': typeof AuthenticatedAdminInicioRoute
  '/admin/pacotes': typeof AuthenticatedAdminPacotesRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/app/diario': typeof AuthenticatedAppDiarioRoute
  '/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/cliente/$clienteId': typeof AuthenticatedAdminClienteClienteIdRoute
  '/app/conteudo/$conteudoId': typeof AuthenticatedAppConteudoConteudoIdRoute
  '/app/eixo/$eixoId': typeof AuthenticatedAppEixoEixoIdRoute
  '/app/etapa/$conteudoId': typeof AuthenticatedAppEtapaConteudoIdRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
  '/admin/monitoramento/': typeof AuthenticatedAdminMonitoramentoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/acompanhamento': typeof AuthenticatedAdminAcompanhamentoRoute
  '/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/admin/diagnostico': typeof AuthenticatedAdminDiagnosticoRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/inicio': typeof AuthenticatedAdminInicioRoute
  '/admin/pacotes': typeof AuthenticatedAdminPacotesRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/app/diario': typeof AuthenticatedAppDiarioRoute
  '/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/cliente/$clienteId': typeof AuthenticatedAdminClienteClienteIdRoute
  '/app/conteudo/$conteudoId': typeof AuthenticatedAppConteudoConteudoIdRoute
  '/app/eixo/$eixoId': typeof AuthenticatedAppEixoEixoIdRoute
  '/app/etapa/$conteudoId': typeof AuthenticatedAppEtapaConteudoIdRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
  '/admin/monitoramento': typeof AuthenticatedAdminMonitoramentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/entrada': typeof AuthenticatedEntradaRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/acompanhamento': typeof AuthenticatedAdminAcompanhamentoRoute
  '/_authenticated/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/_authenticated/admin/diagnostico': typeof AuthenticatedAdminDiagnosticoRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/inicio': typeof AuthenticatedAdminInicioRoute
  '/_authenticated/admin/pacotes': typeof AuthenticatedAdminPacotesRoute
  '/_authenticated/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/_authenticated/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/_authenticated/app/diario': typeof AuthenticatedAppDiarioRoute
  '/_authenticated/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/_authenticated/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/cliente/$clienteId': typeof AuthenticatedAdminClienteClienteIdRoute
  '/_authenticated/app/conteudo/$conteudoId': typeof AuthenticatedAppConteudoConteudoIdRoute
  '/_authenticated/app/eixo/$eixoId': typeof AuthenticatedAppEixoEixoIdRoute
  '/_authenticated/app/etapa/$conteudoId': typeof AuthenticatedAppEtapaConteudoIdRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
  '/_authenticated/admin/monitoramento/': typeof AuthenticatedAdminMonitoramentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/app'
    | '/entrada'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/acompanhamento'
    | '/admin/ajuda'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/conteudos'
    | '/admin/diagnostico'
    | '/admin/equipe'
    | '/admin/inicio'
    | '/admin/pacotes'
    | '/admin/perfil'
    | '/admin/trilhas'
    | '/app/diario'
    | '/app/historico'
    | '/app/jornada'
    | '/app/perfil'
    | '/app/progresso'
    | '/admin/'
    | '/app/'
    | '/admin/cliente/$clienteId'
    | '/app/conteudo/$conteudoId'
    | '/app/eixo/$eixoId'
    | '/app/etapa/$conteudoId'
    | '/api/public/hooks/lembretes'
    | '/admin/monitoramento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/entrada'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/acompanhamento'
    | '/admin/ajuda'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/conteudos'
    | '/admin/diagnostico'
    | '/admin/equipe'
    | '/admin/inicio'
    | '/admin/pacotes'
    | '/admin/perfil'
    | '/admin/trilhas'
    | '/app/diario'
    | '/app/historico'
    | '/app/jornada'
    | '/app/perfil'
    | '/app/progresso'
    | '/admin'
    | '/app'
    | '/admin/cliente/$clienteId'
    | '/app/conteudo/$conteudoId'
    | '/app/eixo/$eixoId'
    | '/app/etapa/$conteudoId'
    | '/api/public/hooks/lembretes'
    | '/admin/monitoramento'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/entrada'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/acompanhamento'
    | '/_authenticated/admin/ajuda'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/conteudos'
    | '/_authenticated/admin/diagnostico'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/inicio'
    | '/_authenticated/admin/pacotes'
    | '/_authenticated/admin/perfil'
    | '/_authenticated/admin/trilhas'
    | '/_authenticated/app/diario'
    | '/_authenticated/app/historico'
    | '/_authenticated/app/jornada'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/progresso'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/cliente/$clienteId'
    | '/_authenticated/app/conteudo/$conteudoId'
    | '/_authenticated/app/eixo/$eixoId'
    | '/_authenticated/app/etapa/$conteudoId'
    | '/api/public/hooks/lembretes'
    | '/_authenticated/admin/monitoramento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksLembretesRoute: typeof ApiPublicHooksLembretesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada': {
      id: '/_authenticated/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof AuthenticatedEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/acompanhamento': {
      id: '/_authenticated/admin/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/admin/acompanhamento'
      preLoaderRoute: typeof AuthenticatedAdminAcompanhamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ajuda': {
      id: '/_authenticated/admin/ajuda'
      path: '/ajuda'
      fullPath: '/admin/ajuda'
      preLoaderRoute: typeof AuthenticatedAdminAjudaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/conteudos': {
      id: '/_authenticated/admin/conteudos'
      path: '/conteudos'
      fullPath: '/admin/conteudos'
      preLoaderRoute: typeof AuthenticatedAdminConteudosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnostico': {
      id: '/_authenticated/admin/diagnostico'
      path: '/diagnostico'
      fullPath: '/admin/diagnostico'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inicio': {
      id: '/_authenticated/admin/inicio'
      path: '/inicio'
      fullPath: '/admin/inicio'
      preLoaderRoute: typeof AuthenticatedAdminInicioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pacotes': {
      id: '/_authenticated/admin/pacotes'
      path: '/pacotes'
      fullPath: '/admin/pacotes'
      preLoaderRoute: typeof AuthenticatedAdminPacotesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/perfil': {
      id: '/_authenticated/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AuthenticatedAdminPerfilRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trilhas': {
      id: '/_authenticated/admin/trilhas'
      path: '/trilhas'
      fullPath: '/admin/trilhas'
      preLoaderRoute: typeof AuthenticatedAdminTrilhasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/diario': {
      id: '/_authenticated/app/diario'
      path: '/diario'
      fullPath: '/app/diario'
      preLoaderRoute: typeof AuthenticatedAppDiarioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/historico': {
      id: '/_authenticated/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AuthenticatedAppHistoricoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jornada': {
      id: '/_authenticated/app/jornada'
      path: '/jornada'
      fullPath: '/app/jornada'
      preLoaderRoute: typeof AuthenticatedAppJornadaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progresso': {
      id: '/_authenticated/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AuthenticatedAppProgressoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/cliente/$clienteId': {
      id: '/_authenticated/admin/cliente/$clienteId'
      path: '/cliente/$clienteId'
      fullPath: '/admin/cliente/$clienteId'
      preLoaderRoute: typeof AuthenticatedAdminClienteClienteIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/monitoramento/': {
      id: '/_authenticated/admin/monitoramento/'
      path: '/monitoramento'
      fullPath: '/admin/monitoramento/'
      preLoaderRoute: typeof AuthenticatedAdminMonitoramentoIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/conteudo/$conteudoId': {
      id: '/_authenticated/app/conteudo/$conteudoId'
      path: '/conteudo/$conteudoId'
      fullPath: '/app/conteudo/$conteudoId'
      preLoaderRoute: typeof AuthenticatedAppConteudoConteudoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/eixo/$eixoId': {
      id: '/_authenticated/app/eixo/$eixoId'
      path: '/eixo/$eixoId'
      fullPath: '/app/eixo/$eixoId'
      preLoaderRoute: typeof AuthenticatedAppEixoEixoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/etapa/$conteudoId': {
      id: '/_authenticated/app/etapa/$conteudoId'
      path: '/etapa/$conteudoId'
      fullPath: '/app/etapa/$conteudoId'
      preLoaderRoute: typeof AuthenticatedAppEtapaConteudoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/lembretes': {
      id: '/api/public/hooks/lembretes'
      path: '/api/public/hooks/lembretes'
      fullPath: '/api/public/hooks/lembretes'
      preLoaderRoute: typeof ApiPublicHooksLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcompanhamentoRoute: typeof AuthenticatedAdminAcompanhamentoRoute
  AuthenticatedAdminAjudaRoute: typeof AuthenticatedAdminAjudaRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConteudosRoute: typeof AuthenticatedAdminConteudosRoute
  AuthenticatedAdminDiagnosticoRoute: typeof AuthenticatedAdminDiagnosticoRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminInicioRoute: typeof AuthenticatedAdminInicioRoute
  AuthenticatedAdminPacotesRoute: typeof AuthenticatedAdminPacotesRoute
  AuthenticatedAdminPerfilRoute: typeof AuthenticatedAdminPerfilRoute
  AuthenticatedAdminTrilhasRoute: typeof AuthenticatedAdminTrilhasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClienteClienteIdRoute: typeof AuthenticatedAdminClienteClienteIdRoute
  AuthenticatedAdminMonitoramentoIndexRoute: typeof AuthenticatedAdminMonitoramentoIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcompanhamentoRoute: AuthenticatedAdminAcompanhamentoRoute,
  AuthenticatedAdminAjudaRoute: AuthenticatedAdminAjudaRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConteudosRoute: AuthenticatedAdminConteudosRoute,
  AuthenticatedAdminDiagnosticoRoute: AuthenticatedAdminDiagnosticoRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminInicioRoute: AuthenticatedAdminInicioRoute,
  AuthenticatedAdminPacotesRoute: AuthenticatedAdminPacotesRoute,
  AuthenticatedAdminPerfilRoute: AuthenticatedAdminPerfilRoute,
  AuthenticatedAdminTrilhasRoute: AuthenticatedAdminTrilhasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClienteClienteIdRoute:
    AuthenticatedAdminClienteClienteIdRoute,
  AuthenticatedAdminMonitoramentoIndexRoute:
    AuthenticatedAdminMonitoramentoIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDiarioRoute: typeof AuthenticatedAppDiarioRoute
  AuthenticatedAppHistoricoRoute: typeof AuthenticatedAppHistoricoRoute
  AuthenticatedAppJornadaRoute: typeof AuthenticatedAppJornadaRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppProgressoRoute: typeof AuthenticatedAppProgressoRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppConteudoConteudoIdRoute: typeof AuthenticatedAppConteudoConteudoIdRoute
  AuthenticatedAppEixoEixoIdRoute: typeof AuthenticatedAppEixoEixoIdRoute
  AuthenticatedAppEtapaConteudoIdRoute: typeof AuthenticatedAppEtapaConteudoIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDiarioRoute: AuthenticatedAppDiarioRoute,
  AuthenticatedAppHistoricoRoute: AuthenticatedAppHistoricoRoute,
  AuthenticatedAppJornadaRoute: AuthenticatedAppJornadaRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppProgressoRoute: AuthenticatedAppProgressoRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppConteudoConteudoIdRoute:
    AuthenticatedAppConteudoConteudoIdRoute,
  AuthenticatedAppEixoEixoIdRoute: AuthenticatedAppEixoEixoIdRoute,
  AuthenticatedAppEtapaConteudoIdRoute: AuthenticatedAppEtapaConteudoIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedEntradaRoute: typeof AuthenticatedEntradaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedEntradaRoute: AuthenticatedEntradaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksLembretesRoute: ApiPublicHooksLembretesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
